version: "3.9"
services:
  web_server:
    build: .
    container_name: web_server
    ports:
      - "3030:3030"
    volumes:
      - ./logs:/app/logs
      - ./DataBase:/app/DataBase
    environment:
      - TZ=Europe/Moscow
