version: "3.9"
services:
  web_server:
    build: .
    container_name: web_server
    ports:
      - "3030:3030"
    volumes:
      - ./logs:/app/logs
      - ./DataBase:/app/DataBase
    environment:
      - TZ=Europe/Moscow
    command: python3.10 web_server.py
  telegram_bot:
    build: .
    container_name: telegram_bot
    ports:
      - "8443:8443"
    volumes:
      - ./logs:/app/logs
      - ./DataBase:/app/DataBase
    environment:
      - TZ=Europe/Moscow
