FROM python:3.10-alpine

# Устанавливаем SQLite
RUN apk add --no-cache sqlite

# Устанавливаем Datasette
RUN pip install --upgrade pip
RUN pip install datasette
RUN pip install peewee

# Копируем файл базы данных в новый контейнер
COPY ./DataBase/database.db /var/lib/sqlite/

# Копируем файлы с классами и миграцией
COPY ./DataBase/model_class.py /app/model_class.py
COPY ./DataBase/manage.py /app/manage.py

# Добавляем сообщение о начале миграции
RUN echo "Starting migration..."

# Выполняем миграцию БД
RUN python -u /app/manage.py migrate

# Добавляем сообщение о завершении миграции
RUN echo "Migration completed."

# Удаляем скопированные файлы
RUN rm /app/model_class.py /app/manage.py

# Добавляем healthcheck
HEALTHCHECK CMD sqlite3 /var/lib/sqlite/database.db "SELECT 1"

# Задаем рабочую директорию
WORKDIR /var/lib/sqlite/

# Устанавливаем точку входа
CMD ["datasette", "serve", "--host", "0.0.0.0", "--port", "5000", "database.db"]
