version: "3.9"
services:
  web_server:
    build: .
    container_name: web_server
    ports:
      - "3030:3030"
    volumes:
      - ./logs:/app/logs
    environment:
      - TZ=Europe/Moscow
    command: python3.10 web_server.py
    networks:
      network_for_bot:
        ipv4_address: 172.28.1.10
      
  telegram_bot:
    build: .
    container_name: telegram_bot
    ports:
      - "8443:8443"
    volumes:
      - ./logs:/app/logs
    environment:
      - TZ=Europe/Moscow
    networks:
      network_for_bot:
        ipv4_address: 172.28.1.20

  db:
    build: 
      context: .
      dockerfile: Dockerfile.db
    container_name: db
    volumes:
      - ./DataBase:/usr/src/app/DataBase
    networks:
      network_for_bot:
        ipv4_address: 172.28.1.30
        
networks:
  network_for_bot:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
