version: "3.9"
services:
  hf_bot:
    build: .
    container_name: hf_bot
    ports:
      - "3030:3030"
    volumes:
      - ./logs:/app/logs
      - ./DataBase:/app/DataBase
    environment:
      - TZ=Europe/Moscow
