FROM alpine:3.13.5

# Устанавливаем SQLite
RUN apk add --no-cache sqlite

# Копируем файл базы данных в новый контейнер
COPY ./DataBase/database.db /usr/src/app/

# Добавляем права на чтение файла
RUN chmod a+r /usr/src/app/database.db

# Задаем рабочую директорию
WORKDIR /app

# Устанавливаем точку входа
CMD ["sqlite3", "/usr/src/app/database.db"]
